version: '2'
services:
  test:
    # build: 
    #   context: .
    #   dockerfile: ./Dockerfile
    environment:
      - ENTRYPOINTD=/source/src/test/docker/entrypoint.d
    image: codercom/code-server:latest
    # command: "/source --auth none --disable-update-check --disable-telemetry"
    container_name: vscodeExtension
    ports:
      - "8080:8080"
    volumes:
      - .:/source
